[workspace]
release_always = false

[changelog]
header = "# Changelog"
body = """
## [{{ version }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
    {%- if group != "dependencies" -%}
        - {{ commit.raw_message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
    {%  else -%}
        - chore(deps): {{ commit.message }}
    {%  endif %}
{%- endfor -%}
{% endfor %}
"""

commit_parsers = [
  { message = "^feat", group = "added" },
  { message = "^changed", group = "changed" },
  { message = '^chore\(deps\)', group = "dependencies" },
  { message = "^chore", group = "chore" },
  { message = "^fix", group = "fixed" },
  { message = "^(ci|minor|refactor|style)", skip = true },
  { message = "^.*", group = "other" },
]
